name: flutter_flow
description: A new flutter plugin project.
version: 0.0.1
author:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  freezed_annotation: ^0.14.1
  googleapis_auth: ^1.1.0
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
  pedantic: ^1.11.0

flutter: